### ISSUE TITLE
Bug in Listing 5.5 (Subscription example)

### ISSUE THREAD

**Issue by JohannesRudolph** [ayende/book#132]
I'm following the subscription example in Listing 5.5 https://github.com/ravendb/book/blob/v4.0/Ch05/Ch05.md#the-subscription-script

```csharp
await subscription.Run(batch =>
{
    foreach (var item in batch.Items)
    {
        SupportCall call = item.Document;
        
        var age = DateTime.Today - call.Started;
        if (age > DateTime.FromDays(14))
            return; // no need to send survey for old stuff

        using (var session = batch.OpenSession())
        {
            var customer = session.Load<Customer>(
                call.CustomerId);

            call.Survey = true;

            session.Store(call, item.ChangeVector, item.Id);

            try
            {
                session.SaveChanges();
            }
            catch (ConcurrenyException)
            {
                // will be retried by the subscription
                return;
            }

            SendSurveyEmailTo(customer, call);
        }
    }
});
```

I think the use of `return` is slightly misleading in here. Since the example uses `foreach` using `return` will actually skip processing the rest of the batch. It's probably more correct to either use `continue` or `batch.Items.ForEach(() => { ... return` 

Also I think the example would be more clear to state `// will be retried in the next batch` and expand in the following paragraph that a `ConcurrencyException` implies the document has changed on the server in between assembling the current subscription batch and saving the modification, which will in turn lead to the updated document to be included in a future subscription batch.

**Comment by JohannesRudolph** [comment]
To clarify re. the `ConcurrencyException` paragraph - the "store.OpenSession note/box" breaks apart this bit of info, even though it's already there. At least that's how I felt reading it the first time (in dead-tree-format aka. paper format).

**Comment by ayende** [comment]
@JohannesRudolph Correct, fixed here: https://github.com/ravendb/book/commit/a009f18c9d2773227135e32eccdd8d190b7ec8ea
