### ISSUE TITLE
Chapter 3 - A common bad practice is to integrate between different applications using a shared database.

### ISSUE THREAD

**Issue by lemonway** [ayende/book#137]
Hello,

I'm not sure if this is the right place to express my opinion

I think that this statement in the [chapter 3](https://github.com/ravendb/book/blob/v4.0/Ch03/Ch03.md) is "half wrong".
"A common bad practice is to integrate between different applications using a shared database."

The readers might understand that sharing database between applications is **always** a bad practices... and it is not true.. 

IMO, the Application A can make choice
* if it will share the same database X of the application X 
* or it will create its own database A and clone (denormalize) informations it wanted from the database X.

it is comparable to make decision at the document-level: if a document will reference to other documents by de-normalization, or by reference id.. Both approaches have its pros and cons depend on the use cases (or context). 

I agree with the bad side about sharing database described in the chapter. But for example:
A database which contains references data (common data) is absolutely valid to share among applications.

**Comment by ayende** [comment]
In nearly every case I have seen, multiple applications sharing the same database ended up in tears.

Different applications have different release schedules, different teams / platforms / priorities. 
Having a shared database adds a *lot* of pain to the system.

Here is a good example:
https://www.amazon.com/Refactoring-Improving-Existing-Addison-Wesley-Signature/dp/0134757599/

That is nearly 500 pages on just how to refactor shared databases. 

Sharing data between databases safely & properly is covered in chapter 8, ETL.
