### ISSUE TITLE
Unable to build book

### ISSUE THREAD

**Issue by Monte-Christo** [ayende/book#144]
Running build.ps1 on Win 10, I get:
```
xelatex not found. Please select a different --pdf-engine or install xelatex
Start-Process: C:\src\Playground\ravendb\book\build.ps1:22
Line |
  22 |      start $output
     |      ~~~~~~~~~~~~~
     | This command cannot be run due to the error: The system cannot find the file specified.

.\Output\Inside RavenDB 4.0.pdf
```

I googled installation of xelatex, and it said to install MikTeX, but i have this installed already. Please add a paragraph to the ReadMe to explain the prerequisites.

Also, is there a book forthcoming on RavenDb 5?

**Comment by ayende** [comment]
Duplicates https://github.com/ravendb/book/issues/146

**Comment by ayende** [comment]
We'll have an updated book for the 6.0 edition, expected Q2 2022
