### ISSUE TITLE
Build.ps1 throws error using xelatex

### ISSUE THREAD

**Issue by Monte-Christo** [ayende/book#145]
After manually adding the path to xelatex (which I found in `%localappdata%\Programs\MiKTeX\miktex\bin\x64` and editied the build.ps1 script accordingly), I am getting more errors:

````
Error producing PDF.
! Argument of \__sys_tmp:w has an extra }.
<inserted text>
                \par
l.80 ...c__kernel_sys_dvipdfmx_version_int { 0 } }

Start-Process: D:\src\Playground\ravendb\book\build.ps1:22
Line |
  22 |      start $output
     |      ~~~~~~~~~~~~~
     | This command cannot be run due to the error: The system cannot find the file specified.

````

I must say, this is frustrating as hell. Someone please just provide a pdf, preferably of version 5.

**Comment by ayende** [comment]
Duplicates https://github.com/ravendb/book/issues/146
