### ISSUE TITLE
build.ps1 throws error with pdflatex

### ISSUE THREAD

**Issue by Monte-Christo** [ayende/book#146]
After switching to pdflatex instead of xelatex, in build.ps1 I am getting another error:

````
Error producing PDF.
! Package inputenc Error: Invalid UTF-8 byte sequence.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...

l.15435 \passthrough{\lstinline!Mart├¡n Sommer!}

Try running pandoc with --pdf-engine=xelatex.
Start-Process: D:\src\Playground\ravendb\book\build.ps1:22
Line |
  22 |      start $output
     |      ~~~~~~~~~~~~~
     | This command cannot be run due to the error: The system cannot find the file specified.

.\Output\Inside RavenDB 4.0.pdf
````
I am sorry, but I don't have time to become an expert in LaTeX just to get a PDF copy of the (as it appears, outdated) book produced.

**Comment by ayende** [comment]
You can get the PDF from the releases, here:

https://github.com/ravendb/book/releases

Better yet, use: https://ravendb.net/learn/inside-ravendb-book/

That gives you both the production quality PDF as well as the ability to read online.
