### ISSUE TITLE
Terminology: ACID vs ACID-compliant?

### ISSUE THREAD

**Issue by SeanKilleen** [ayende/book#20]
In Ch01, you mention that RavenDB is an ACID database.

I'm tempted to correct this to "ACID-compliant" because it adheres to the rules/guidelines of ACID, but I'm not sure how you feel about that language.

Thoguhts?

**Comment by ayende** [comment]
ACID compliant assumes that there is an ACID standard to be compliant with, no?

**Comment by SeanKilleen** [comment]
@ayende true -- What if we say that it's a database that adheres to the concept of ACID?

**Comment by ayende** [comment]
The intent in there is to ensure that people understand that the data is safe.
That is, we actually have transactions so you don't get partial data if there is a failure midway, and you don't have to worry about someone pulling the plug, because the data is persisted on disk

**Comment by SeanKilleen** [comment]
Realized that this can probably be closed. :)
