### ISSUE TITLE
Docker Example broken

### ISSUE THREAD

**Issue by ChristianSauer** [ayende/book#53]
I tried to use your docker example from page 17 and encountered several issues:
1. the generated pdf contains non default characters for several symbols like "=" - so copy paste does not work.
2. Even when fixed, the docker command starts a server which refuses unsecured connections, it seems liike the correct command is: docker run -e UNSECURED_ACCESS_ALLOWED=PublicNetwork -p 8080:8080 ravendb/ravendb
3. Your docker hub readme contains linke to powershell scripts, but the links are broken (Run Ubuntu-based image: run-ubuntu1604.ps1)
4. I found the the scripts on Github, but the documentation was sparse, e.g. there was no mention that you would probably use the AuthenticationDisabled switch

**Comment by gregolsky** [comment]
Links on hub fixed https://hub.docker.com/r/ravendb/ravendb/
Thanks for taking time to report that.

**Comment by ayende** [comment]
@ChristianSauer Thanks for the report, all fixed now.
