### ISSUE TITLE
Code Listings in PDF broken

### ISSUE THREAD

**Issue by ChristianSauer** [ayende/book#55]
When copy-pasting code from the PDF, most examples are broken.
For example Listing 2.4 becomes this:

var s t o r e = new DocumentStore
{
Urls = { ” http :// l o c a l h o s t :8080” } ,
Database = ” Tasks ”
} ;
s t o r e . I n i t i a l i z e ( ) ;

**Comment by ayende** [comment]
How did you get this? Using the latest version, and in Acrobat Reader, I'm able to properly copy/paste.

**Comment by ChristianSauer** [comment]
I am using the odd reader built into Chrome, newest version 




Outlook for Android herunterladen







On Tue, Oct 31, 2017 at 11:00 AM +0100, "Ayende Rahien" <notifications@github.com> wrote:












How did you get this? Using the latest version, and in Acrobat Reader, I'm able to properly copy/paste.

**Comment by ayende** [comment]
Okay, managed to reproduced this in 4.6 release, doesn't happen on the current build. 
I'll make a release once I'm done with chapter 9 that would resolve this.

**Comment by ChristianSauer** [comment]
Thx!

**Comment by ayende** [comment]
A new release was made, this should fix the issue
This also has much of the book actually professionally edited, so you might want to read back, it should make more sense now :-)
