### ISSUE TITLE
Listing 2.14 - code not working with newest Nuget Client

### ISSUE THREAD

**Issue by ChristianSauer** [ayende/book#56]
Urls and Database appears to be have renamed to Url and DefaultDatabase.

Is this type of proofreading even useful for you? I'm working through the examples and would report problems here - but if I just annoy you, it's no problem to stop it.

**Comment by ayende** [comment]
@ChristianSauer I'm _really_ loving this, yes. Please send any such issues that you have here.
In fact, send me your snail mail address and tshirt size, I'll send one for you.

Regarding the actual issue, `Url` & `DefaultDatabase` are used in 3.5, `Urls` and `Database` is using in 4.0.
Make sure that in Nuget, you use the 4.0 release (set pre-release to true).

**Comment by ChristianSauer** [comment]
@ayende Thx! Will do.

I searched directly on Nuget and forget to add the myget package source, sorry.
