### ISSUE TITLE
DockerFile on Github / this book: Improve run Documentation

### ISSUE THREAD

**Issue by ChristianSauer** [ayende/book#58]
After a lot of try and error (why does the python client not connect? Http works fine!) I digged into the Urls, Python barfed up and discovered that http://nbsauerch03:8080/topology?name=SomeDb
returned results such as:

```
{
  "Nodes": [
    {
      "Url": "http://<containerid>:8080",
      "ClusterTag": "A",
      "ServerRole": "Member",
      "Database": "SomeDb"
    }
  ],
  "Etag": -1
}
``` 
which does not work when seen from an external client - e.g. if I use the standard Docker-MobyLinux on Windows configuration. The Python Client then uses this Urls to try to get more Information, but fails with a TopologyException since the URL cannot be resolved.
Setting  PUBLIC_SERVER_URL=http://localhost:8080 fixes that, but I#m unsure if I have to set other values, too.

**Comment by ayende** [comment]
Yes, you'll need the public server details there, that is all you'll need.
We are working on making this easier.
