### ISSUE TITLE
Attachments: Clarify ACID or base nature?

### ISSUE THREAD

**Issue by ChristianSauer** [ayende/book#60]
When I was rereading the newest version of your book on christmas, I was wondering if attachments are BASE or ACID - e.g. when is the document considered "complete" on the server?
When the json is saved on disk or if the json and all attachments are on disk?
If the first, this would be good to know since there might be situations where a document without attachment is not really usable.

**Comment by ayende** [comment]
@ChristianSauer Attachments are saved as part of the same transaction as the document update.
In other words, any update to attachment and document always happen together.

This is discussed here: 
https://github.com/ravendb/book/blob/v4.0/Ch03/Ch03.md#attachments-and-binary-data
