### ISSUE TITLE
Filipino Translation/Localization

### ISSUE THREAD

**Issue by themarshann** [ayende/book#72]
Hi,
I'm interested in contributing for this project and I'd like to be of help in translating this into the Filipino language. I think it'll be helpful for this to have a wider reach. Hope you'll consider.

Thanks :)

**Comment by ayende** [comment]
That would be great, yes.

**Comment by themarshann** [comment]
Shall I make a separate repository for the translated files then? Or just create new files and have them named as `Ch02-fil.md` for example?
Thanks for the quick response :)

**Comment by ayende** [comment]
I think creating a sibling file would work, yes.

**Comment by themarshann** [comment]
Okay, thanks. Will slowly start doing the translations then :)
